use_frameworks!

platform :ios, '12.0'

target 'MRZScanner_Example' do
  pod 'MRZScanner', :path => '../'

  target 'MRZScanner_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "MRZScanner"
              target.build_configurations.each do |config|
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
              end
          end
      end
  end
  
end
